name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Install huggingface-hub
        run: pip install huggingface-hub
      - name: Squash and Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git checkout --orphan new-main
          git add -A
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git commit -m "Initial commit"
          git remote add space https://shreyasarya:$HF_TOKEN@huggingface.co/spaces/shreyasarya/ML
          git push -f space new-main:main
          echo "Push complete!"
